//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.Data.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cholesterol
    {
        public int TestID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> LDL { get; set; }
        public Nullable<int> HDL { get; set; }
        public Nullable<int> VLDL { get; set; }
        public Nullable<int> Total_Cholesterol { get; set; }
        public Nullable<int> Triglycerides { get; set; }
        public Nullable<int> Non_HDL { get; set; }
        public Nullable<decimal> Total_HDL_Ratio { get; set; }
        public Nullable<int> apoB100_calc { get; set; }
        public Nullable<int> LDL_R { get; set; }
        public Nullable<decimal> Lp_a_ { get; set; }
        public Nullable<int> IDL { get; set; }
        public Nullable<int> Remnant_Lipo__IDL___VLDL3_ { get; set; }
        public Nullable<int> HDL_2 { get; set; }
        public Nullable<int> HDL_3 { get; set; }
        public Nullable<int> VLDL_3 { get; set; }
        public Nullable<decimal> LDL1_Pattern_A { get; set; }
        public Nullable<decimal> LDL_2_Pattern_A { get; set; }
        public Nullable<decimal> LDL_3_Pattern_B { get; set; }
        public Nullable<decimal> LDL_4_Pattern_B { get; set; }
        public string LDL_Density { get; set; }
        public Nullable<int> Systolic { get; set; }
        public Nullable<int> Diastolic { get; set; }
        public string Comment { get; set; }
    }
}
