//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.Data.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergyBill
    {
        public int BillID { get; set; }
        public Nullable<System.DateTime> BillEnd { get; set; }
        public Nullable<int> DaysInPeriod { get; set; }
        public Nullable<int> KwH { get; set; }
        public Nullable<decimal> ElectricCost { get; set; }
        public Nullable<decimal> KwHPrice { get; set; }
        public Nullable<int> Meter { get; set; }
        public Nullable<int> SolarProduction { get; set; }
        public Nullable<int> SolarUsage { get; set; }
        public Nullable<decimal> SolarSavings { get; set; }
        public Nullable<decimal> Therms { get; set; }
        public Nullable<decimal> GasCost { get; set; }
        public Nullable<int> AvgTemp { get; set; }
        public Nullable<int> Thermostat { get; set; }
        public string Mode { get; set; }
        public string Comment { get; set; }
    }
}
