//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.Data.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestmentTransaction
    {
        public int InvestmentTransactionID { get; set; }
        public int DataPointID { get; set; }
        public Nullable<int> ReserveCategoryID { get; set; }
        public string Description { get; set; }
        public decimal Basis { get; set; }
        public System.DateTime InvestmentDate { get; set; }
    
        public virtual tblDataPoint tblDataPoint { get; set; }
        public virtual ReserveCategory ReserveCategory { get; set; }
    }
}
