//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.Data.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyData
    {
        public byte MonthID { get; set; }
        public short YearID { get; set; }
        public Nullable<bool> Initialized { get; set; }
        public Nullable<decimal> Savings { get; set; }
        public byte UserID { get; set; }
    }
}
