//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.Data.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSupplement
    {
        public int Id { get; set; }
        public short StrengthMg { get; set; }
        public byte Dose { get; set; }
        public int ProductId { get; set; }
        public int SupplementId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplement Supplement { get; set; }
    }
}
