//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.Data.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDataPoint
    {
        public int DataPointID { get; set; }
        public System.DateTime DataDate { get; set; }
        public decimal DataValue { get; set; }
        public short AccountFundID { get; set; }
        public string Type { get; set; }
    }
}
