//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HouseholdEntities : DbContext
    {
        public HouseholdEntities()
            : base("name=HouseholdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BudgetCategory> BudgetCategories { get; set; }
        public virtual DbSet<BudgetLineItem> BudgetLineItems { get; set; }
        public virtual DbSet<DeepReserve> DeepReserves { get; set; }
        public virtual DbSet<EnergyBill> EnergyBills { get; set; }
        public virtual DbSet<MonthlyData> MonthlyDatas { get; set; }
        public virtual DbSet<ReserveAccount> ReserveAccounts { get; set; }
        public virtual DbSet<ReserveCategory> ReserveCategories { get; set; }
        public virtual DbSet<ScheduledTran> ScheduledTrans { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Cholesterol> Cholesterols { get; set; }
    }
}
