//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReserveCategory
    {
        public int ReserveCategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> Display { get; set; }
        public Nullable<bool> Archived { get; set; }
    }
}
