//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.SharedKernel.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSupplement
    {
        public int Id { get; set; }
        public decimal StrengthMg { get; set; }
        public byte Dose { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid SupplementId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductSupplement ProductSupplement1 { get; set; }
        public virtual ProductSupplement ProductSupplement2 { get; set; }
        public virtual Supplement Supplement { get; set; }
    }
}
