//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.SharedKernel.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountFund
    {
        public short AccountFundID { get; set; }
        public byte FundID { get; set; }
        public byte AccountID { get; set; }
        public bool Active { get; set; }
    }
}
