//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.SharedKernel.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public byte AccountID { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
        public string AccountNumber { get; set; }
        public string CompanyName { get; set; }
        public bool Active { get; set; }
        public bool Display { get; set; }
    }
}
