//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Household.Data.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Finance : DbContext
    {
        public Finance()
            : base("name=Finance")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BudgetCategory> BudgetCategories { get; set; }
        public virtual DbSet<BudgetLineItem> BudgetLineItems { get; set; }
        public virtual DbSet<DeepReserve> DeepReserves { get; set; }
        public virtual DbSet<EnergyBill> EnergyBills { get; set; }
        public virtual DbSet<MonthlyData> MonthlyDatas { get; set; }
        public virtual DbSet<ReserveAccount> ReserveAccounts { get; set; }
        public virtual DbSet<ReserveCategory> ReserveCategories { get; set; }
        public virtual DbSet<ScheduledTran> ScheduledTrans { get; set; }
        public virtual DbSet<tblDataPoint> tblDataPoints { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<tblAccountFund> tblAccountFunds { get; set; }
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblFund> tblFunds { get; set; }
    }
}
